### ISSUE TITLE
Artwork - Rome Visual Refresh

### ISSUE THREAD

**Issue by flaki** [RustFestEU/brand#1]
# Visual Refresh for RustFest Rome
## Artwork

Elio Qoshi and his team has provided a proposal for the Visual Refresh project for the upcoming RustFest Rome conference which is currently being evaluated by the team members.

![rf-visual-identity](https://user-images.githubusercontent.com/2089432/46654493-460d7a00-cba9-11e8-84a0-cda3cbba3a1e.jpg)

> The original files are available in the [RustFest Drive Rome folder](https://drive.google.com/drive/u/0/folders/1HxQEYERvrz-ygIY4dnuDTzw3by67ljrH) _(accessible only by organizing team members)_

**Comment by flaki** [comment]
The initial impressions of team members (from mailing list and private team discussions) were generally positive, praising the art direction of the artwork presented and interested in seeing this presented at the Rome event.

_Further comments can be added and the proposal discussed below._

**Comment by elioqoshi** [comment]
Thanks for initiating this @flaki !
As you can see, we provided artwork for Staff and Speakers. If you wish to have T-Shirts/Badges/similar for attendees, we can also do an additional version for them.
