### ISSUE TITLE
Logo - Rome Visual Refresh

### ISSUE THREAD

**Issue by flaki** [RustFestEU/brand#2]
# Visual Refresh for RustFest Rome
## Logo

Elio Qoshi and his team has provided a logo proposal and various alternates for the Visual Refresh project of the upcoming RustFest Rome conference, which is currently being evaluated by the team members.

![rf-logo-proposals](https://user-images.githubusercontent.com/2089432/46655519-19a72d00-cbac-11e8-889f-1f7f0b38cfac.jpg)
![rf-logo-alts](https://user-images.githubusercontent.com/2089432/46655526-1e6be100-cbac-11e8-986a-786c70919d08.jpg)

> The original files are available in the [RustFest Drive Rome folder](https://drive.google.com/drive/u/0/folders/1HxQEYERvrz-ygIY4dnuDTzw3by67ljrH) _(accessible only by organizing team members)_

**Comment by flaki** [comment]
On previous (non-public) mailing list and team discussions the organizers expressed concerns about moving too far away from the original cog/wheel logo, and requested that we keep the continuity with the previous events (see event-specific folders [in this repository](../blob/master/)).

The continuity is best seen preserved in keeping the general shape of the original RustFest logo (the [rounded cog/wheel](../blob/master/Berlin%202016/rustfest.png), which itself is a reference to the original [Rust logo](https://www.rust-lang.org/logos/rust-logo-blk.svg)).

As per the general consensus among team members, this above-stated continuity is meant more to be preserved in the shape, while the colors can be somewhat liberally chosen and/or tweaked.

The team is thankful for the proposed explorations that move away slightly (or more radically) from the current/original logo, but would like to have logo proposals akin to the Gladius (LOGO 1) proposal explored further, keeping in mind the above requested continuity.

_Further comments can be added and the proposal discussed below._

**Comment by flaki** [comment]
Also, from previous mailing list/team discussions:

The team would prefer to move away from symbols of war, if possible (this was a major concern against the Gladius proposal itself); but would like to to continue on the tradition of having the local (Rome/Italy/Classic Roman) themes represented in the logo similarly to the previous editions.

**Comment by sebasmagri** [comment]
Reposting here for further reference:

> Hi!
> 
> I also like the thicker Solomon knot versions better, and share the view of getting away of war symbols.
> 
> If we want to remain on the Rome Empire references but also remain close to the "cog" RustFest logo, we could also consider some references to Roman science and engineering (more compatible with our ideas I think), like abstracting the arc shapes in aqueducts or amphiteater/forum related shapes in a simple concentric pattern that can be combined with the cog.
> 
> 2 euro cents.
> 
> Best Regards,

**Comment by elioqoshi** [comment]
Thanks for the very insightful and organized feedback!

Judging from the comments, I'd agree to keep the same RustFest EU Logo, but change the color palette for every edition (in this case, Rome Edition). It's important to strike the right balance between consistency and uniqueness. In the past proposal we followed the opposite as you can see: same color palette, different logo. We can try the opposite now. With the artwork providing additional look and feel to the Rome edition, there should be plenty of space to give Roman character to the conference I believe.

This is my input of course.  I will circle back with Ergi, my designer colleague who worked on the artwork as well.

**Comment by elioqoshi** [comment]
Hi folks!

Attached the directions proposed. I had a chat with Flaki IRL during MozFest and we some issues with a tweaked logo as the main rustfest logo doesn't offer enough flexibility.

[RustFest Rome18 - Logo Altenatives 2.pdf](https://github.com/RustFestEU/brand/files/2526006/RustFest.Rome18.-.Logo.Altenatives.2.pdf) 

Also on Dropobox: https://www.dropbox.com/s/9gehzhxiiaovqle/RustFest%20Rome%202018%202.zip?dl=0

So in the following I'm suggesting a revised version with an updated color palette based by the design proposals of my colleague @ergish:

[Proposal Revised.pdf](https://github.com/RustFestEU/brand/files/2526019/Proposal.Revised.pdf)

It basically has a more color contrast friendly color palette while keeping the same RustFest logo shape and only changing the colors of the logo.

**Comment by skade** [comment]
I totally want stickers of the vespa logo :)

Can we add "safe, secure, souped up"

**Comment by elioqoshi** [comment]
@skade forgot to mention that: in fact @flaki specifically asked to turn them into stickers as well so definitely gonna do that :)

**Comment by badboy** [comment]
Big fan of the Vespa logo and those would indeed make a good sticker.

**Comment by skade** [comment]
I like that a lot.

**Comment by ergish** [comment]
Hi there guys, nice to meet you! :)

So thank you for your feedback and your suggestions! 
Here's a preview of the T-shirts and the stickers that me and my colleague @elioqoshi  are proposing:

[Tshirt Design 1-5 - Mockup.pdf](https://github.com/RustFestEU/brand/files/2542693/Tshirt.Design.1-5.-.Mockup.pdf)
[Stickers 1-11 - Mockup.pdf](https://github.com/RustFestEU/brand/files/2542694/Stickers.1-11.-.Mockup.pdf)

Also, in the dropbox link there are the updated files of the brand identity presentation, the logo with all it's alternations and the ready for print PDFs: 
https://www.dropbox.com/sh/8bypb8mptxsj9i0/AAAH2TfzyZo8vhav4B4cby6va?dl=0

Just let us know if you have any other suggestions.

**Comment by flaki** [comment]
Hey @ergish this looks great!

The T-Shirt v1 is almost perfect IMO for the staff t-shirt - I'd just like to request that "2018" is always the full 4-numeral year when "Rome 18" is on its separate line. v2 and v5 I could imagine as T-shirts for attendees up for purchase we will figure out how will this work on tomorrow's call and get back to you by Wednesday!

The stickers are an instant get, I love 1,2,3 (@skade!!!!) and 7 (the Ferris one) the most. Here I also have a similar request to above - to have 1,3 & 7 include the full year (ROME 2018) when this is written on one of the handles of the RustFest wheel. Apart from that, please share the sources of these with @janerikr (janerik@rustfest.eu) so we can order the stickers ASAP.

Thanks again for the great work this is going to be very well received, I can already tell!

**Comment by badboy** [comment]
Can we get a comma into the "Safe Secure Souped Up" version?
=> "Safe, Secure, Souped Up".

I'd like to order those as stickers this week.

**Comment by ergish** [comment]
Hi guys,

Thank you for the appreciation and your precise feedback!

We replaced "18" with "2018" in the logo and also in every file of the brand identity so now everywhere it will appear "RUSTFEST ROME 2018". 
"Safe, Secure, Souped Up" is also updated.

All the files are on dropbox (no mockups included): https://www.dropbox.com/sh/v2bzic913pj6k9h/AADzus0JrGOEcSkmf9UbCLWya?dl=0

@badboy The stickers are ready and split in separate PDF files:
https://www.dropbox.com/sh/ys3aafsww6nrigi/AAA5I1ZlP__IOelnvcWsFhapa?dl=0

Thank You!

**Comment by flaki** [comment]
Hi @ergish!

The team has made a decision. We will use Design 1 for a staff shirt (could you please include an asset representing the back of the t-shirt, with the "STAFF" text?)

Also Design 2 will be our attendee T-shirt, could you please include an updated visualization/mockup of the T-shirt with that design in the above Dropbox (with the correct RustFest 2018 text) - one that we could use in promoting the T-shirt?

Thanks!

**Comment by elioqoshi** [comment]
@flaki Are you okay with these design assets be released under CC-BY 4.0 ? If not, let us know what license you prefer.

@ergish can you do a final cleanup of the design files and afterwards @AnXh3L0 can upload them on our repo in Open Standard Design formats.

**Comment by elioqoshi** [comment]
ping @ergish @anxh3l0

**Comment by badboy** [comment]
Having these under an open license is perfect. CC BY 4.0 sounds good to me.

**Comment by skade** [comment]
CC-BY 4.0 also sounds good to me.

**Comment by ergish** [comment]
Hello everyone,

@flaki Thank you for that! The dropbox folder now contains only the final files. Also the mockup images are in their corresponding folders.

@elioqoshi @AnXh3L0 The files can be downloaded here:
https://www.dropbox.com/sh/v2bzic913pj6k9h/AADzus0JrGOEcSkmf9UbCLWya?dl=0

**Comment by elioqoshi** [comment]
Great, thanks! @anxh3l0 do your magic? 💯

**Comment by elioqoshi** [comment]
@flaki I think this is good to go. We will just push them to our repo as open standards friendly files for better archiving

**Comment by AnXh3L0** [comment]
Hi everyone,

Here you'll find the assets, all cleaned up SVG-s and exported in PDF/PNG.

https://github.com/uracreative/works/tree/master/RustFestRome%202018

**Comment by elioqoshi** [comment]
@anxh3l0 thanks! Can you also add a CC-BY license notice with the original author being RustFest.eu ?

**Comment by RafaelaWetzel** [comment]
Hey @elioqoshi,
could you add the files to our repository as well? Thanks!

**Comment by elioqoshi** [comment]
@AnXh3L0 will be able to do that. Could you do a PR please, Anxhelo?

**Comment by AnXh3L0** [comment]
Sure, PR is done :)
